### ISSUE TITLE
[FEATURE]: Levitated Chat Screen

### ISSUE THREAD

**Issue by 628496** [KessokuTeaTime/Edgeless-Chat-Screen#7]
### Feature Description

It would be better if there is a config file so that the chat screen can be moved elsewhere.
(My version is 1.20.1)
### Propose Reason

As a Pojavlauncher player, it is annoying that the chat screen is covered by the keyboard.
![3CA00534-7A10-4FD7-A306-DBA4E857D98B](https://github.com/user-attachments/assets/1eb6170e-ca38-4c64-a289-2514cc32b7c7)

**Comment by KrLite** [comment]
I'm sorry for your inconvenience, however, I believe that this is an invalid feature for this mod.

Reasons:

- This mod is only intended to make chat screens _edgeless_ without any other functionalities, in order to keep the mod **simple** and **direct.** So there won't be any plans to implement a feature like moving the chat screen elsewhere.
- Your request seems to be a fake need. First of all, **Minecraft Java Edition** doesn't guarantee compatibility on mobile platforms at all, so inconveniences always happens, and that shouldn't be an excuse to request these game or mod developers to implement mobile platforms compatibilities. Secondly, this isn't a problem on the compatible platforms, so it will not be an implementable feature neither. Last but not least, it may not be a must for you to do everything on mobile using builtin keyboards, maybe you can find other solutions like voice to text or physical keyboards to help improve your game experience, instead of asking for a new feature. And, this isn't actually just a matter of _configs,_ it is a whole new function, that you missed the point.
- **Many of the aspects aren't technically implementable.** It needs tons of work to compatible platforms of different devices, and on iOS, it is not able to tell the top height of the keyboard from a simple Java program. It also needs a lot of hack to make everything still working with chat screen levitated - the interaction bounds, the history chat panel...

**This issue will be closed as not completed.**
